services:
  - type: web
    name: klinika
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn klinika_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: klinika_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        sync: false
